'use server';
/**
 * @fileOverview An AI agent that generates a detailed narrative insight for a given topic or coin.
 *
 * - getMarketNarratives - A function that generates the detailed narrative.
 * - GetMarketNarrativesInput - The input type for the function.
 * - GetMarketNarrativesOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetMarketNarrativesInputSchema = z.object({
  topic: z.string().describe('The topic, market segment, or specific coin name to analyze for narratives (e.g., "Meme Coins", "Solana Ecosystem", "Dogecoin").'),
});
export type GetMarketNarrativesInput = z.infer<typeof GetMarketNarrativesInputSchema>;

const DetailedNarrativeSchema = z.object({
  analyzedTopic: z.string().describe('The coin or topic that was analyzed.'),
  generatedNarrative: z.string().describe('The main 1-3 paragraph narrative insight generated by the AI. This should cover the current market tone, key catalysts or concerns, and probable storyline, synthesizing insights as if from sentiment scores, on-chain trends, and news buzz.'),
  marketTone: z.string().describe('The current overall market tone regarding the topic (e.g., "Bullish with caution", "Speculative frenzy", "Consolidating after volatility"). This should be derived from the simulated analysis.'),
  keyCatalystsOrConcerns: z.array(z.string()).describe('A list of 2-4 key catalysts that might drive price movement or key concerns to watch out for, based on simulated data.'),
  probableStoryline: z.string().describe('A plausible short-term storyline explaining why the coin might pump or dump soon, based on simulated current factors and market psychology.'),
  strategicOutlook: z.string().describe('A brief strategic outlook, considering short-term vs. long-term perspectives or potential pivot points, informed by the simulated analysis.'),
  confidence: z.enum(['High', 'Medium', 'Low']).describe("The AI's confidence level in this narrative assessment."),
  analysisDate: z.string().describe("The date this narrative analysis was performed."),
});
export type DetailedNarrative = z.infer<typeof DetailedNarrativeSchema>;


const GetMarketNarrativesOutputSchema = z.object({
  narrativeInsight: DetailedNarrativeSchema,
  disclaimer: z
    .string()
    .default('Narrative insights are AI-generated based on simulated market understanding and publicly available information. This does not constitute financial advice. Narratives can shift rapidly and are highly speculative. DYOR.')
    .describe('Standard disclaimer for narrative analysis.'),
});
export type GetMarketNarrativesOutput = z.infer<typeof GetMarketNarrativesOutputSchema>;

export async function getMarketNarratives(input: GetMarketNarrativesInput): Promise<GetMarketNarrativesOutput> {
  return getMarketNarrativesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getDetailedMarketNarrativePrompt',
  input: {schema: GetMarketNarrativesInputSchema},
  output: {schema: GetMarketNarrativesOutputSchema},
  prompt: `You are an AI crypto analyst specializing in generating compelling short-term narratives for the coin or topic: {{{topic}}}.
Your primary task is to generate a detailed narrative insight.

To do this, you must simulate a deep understanding and analysis of various factors, including:
-   **Market Sentiment**: Act as if you have analyzed sentiment scores, trending keywords, and overall social media discussion (e.g., Twitter mentions, Reddit positivity).
-   **On-chain Trends**: Simulate insights from on-chain data, such as wallet activity (e.g., new vs. active wallets, whale movements), and trading volume delta (e.g., volume spikes on DEXs).
-   **News Buzz**: Act as if you are aware of top news titles, recent developments, or significant announcements related to {{{topic}}}.
-   **Broader Crypto Market Context**: Consider related narratives (e.g., AI tokens, political meme coins, DeFi trends) and overall market conditions.

Based on your simulated analysis of these factors, provide a response structured according to the JSON output schema. Specifically, ensure the following:

1.  **'analyzedTopic'**: Confirm the topic you analyzed: "{{topic}}".
2.  **'generatedNarrative'**: This is the core of your output. Craft a 1-3 paragraph insight. This narrative must synthesize your simulated findings from sentiment, on-chain data, and news buzz. It should clearly address:
    *   The current market tone surrounding "{{topic}}".
    *   Key catalysts (positive drivers) or concerns (negative drivers) influencing "{{topic}}".
    *   A probable storyline explaining why "{{topic}}" might experience significant price movement (pump/dump) in the near future.
3.  **'marketTone'**: Summarize the overall market tone for "{{topic}}" (e.g., "Cautiously optimistic with bullish undertones from social media", "Highly speculative with FOMO building due to recent whale activity", "Bearish sentiment dominating due to negative news"). This should be a direct reflection of your simulated sentiment analysis.
4.  **'keyCatalystsOrConcerns'**: List 2-4 distinct key catalysts (e.g., "Simulated upcoming product launch," "Sudden surge in influencer mentions based on social chatter analysis") or concerns (e.g., "Simulated regulatory uncertainty from news analysis," "Decreasing developer activity observed from conceptual on-chain metrics").
5.  **'probableStoryline'**: Provide a concise, plausible storyline for "{{topic}}". For example: "If Bitcoin continues its rally, {{{topic}}} (simulated as a high-beta asset) could see amplified gains, driven by renewed retail interest apparent in social media trends and an uptick in simulated new wallet creation." or "A recent critical news piece and simulated large outflows from whale wallets suggest {{{topic}}} may face a corrective dip before finding support."
6.  **'strategicOutlook'**: Offer a brief strategic outlook. For instance: "Based on the current narrative, {{{topic}}} appears to be a short-term speculative play; long-term viability seems questionable without further utility development, as indicated by simulated on-chain data."
7.  **'confidence'**: State your confidence ('High', 'Medium', 'Low') in this overall narrative assessment.
8.  **'analysisDate'**: This will be set programmatically to the current date.

Your overall tone must be insightful, hype-aware, and market-literate. Focus on speculation catalysts and market psychology when crafting the narrative.
The 'disclaimer' will be automatically added by the system if not generated.
`,
});

const getMarketNarrativesFlow = ai.defineFlow(
  {
    name: 'getMarketNarrativesFlow',
    inputSchema: GetMarketNarrativesInputSchema,
    outputSchema: GetMarketNarrativesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (output) {
      // Ensure analyzedTopic is set correctly, even if LLM generates it in narrativeInsight
      output.narrativeInsight.analyzedTopic = input.topic;
      output.narrativeInsight.analysisDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
      if (!output.disclaimer) {
        output.disclaimer = 'Narrative insights are AI-generated based on simulated market understanding and publicly available information. This does not constitute financial advice. Narratives can shift rapidly and are highly speculative. DYOR.';
      }
    }
    return output!;
  }
);

